# Generated by Django 4.2.3 on 2026-10-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_digitalevidence_blockchainblock_evidenceverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
