# Generated by Django 5.2.17 on 2026-10-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_registration_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalevidence',
            name='image_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
