# Generated by Django 5.2.17 on 2026-10-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_digitalevidence_is_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalevidence',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Tampered', 'Tampered'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
